bc_weight: 0.1
checkpoint: true
clip_ratio: 0.2
cost_crash: 150.0
cost_limit: 1
cost_scale_mu: 200
dt: 0.1
ent_coef: 0.01
env_id: Intersection-Lag-v0
epochs: 200
gae_lambda: 0.95
gamma: 0.99
lambda_init: 0.1
lambda_lr: 0.005
lr: 0.0002
max_accel: 3.2
max_grad_norm: 0.5
minibatch_size: 128
num_envs: 4
num_steps: 2048
reward_collision: -200.0
reward_success: 200.0
robot_radius: 0.3328
save_gif_freq: 50
seed: 42
target_pos:
- 1.25
- 0.0
update_epochs: 10
v_limit: 1.5
vf_coef: 0.5
w_comfort: 0.697
w_overspeed: 72.7
w_progress: 20
w_time_penalty: 0.5
